version: "3.9"

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: portfolio-chat-db
    environment:
      POSTGRES_USER: rag
      POSTGRES_PASSWORD: ragpw
      POSTGRES_DB: ragdb
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
